# Generated by Django 2.1.7 on 2019-02-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wings', '0002_auto_20190219_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('member_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('comment', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
